# Generated by Django 5.2.3 on 2025-07-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='distrations',
        ),
        migrations.AddField(
            model_name='session',
            name='expected_duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
